@AbapCatalog.compiler.compareFilter: true
@AbapCatalog.preserveKey: true
@AbapCatalog.sqlViewName: 'ZEM_MBPCUSTKNVI'

@AccessControl.authorizationCheck: #NOT_REQUIRED

@EndUserText.label: 'Customer KNVI'

@ObjectModel.usageType: { serviceQuality: #X, sizeCategory: #XL, dataClass: #MIXED }

define view ZIM_MASS_BP_CUST_TAX
  as select from knvi

    inner join   kna1   as _kna1   on knvi.kunnr = _kna1.kunnr
    inner join   but000 as _but000 on knvi.kunnr = _but000.partner

{
  key _but000.partner          as PARTNER,
  key knvi.aland               as ALAND,
  key knvi.tatyp               as TATYP,

      knvi.kunnr               as KUNNR,
      _kna1.zz1_crreason_cus   as zz1_crreason_cus,
      _but000.type             as Type,
      _but000.bpkind           as Bpkind,
      _but000.bu_group         as Bu_Group,
      _but000.bpext            as Bpext,
      _but000.bu_sort1         as Bu_Sort1,
      _but000.bu_sort2         as Bu_Sort2,
      _but000.source           as Source,
      _but000.title            as Title,
      _but000.xdele            as Xdele,
      _but000.xblck            as Xblck,
      _but000.augrp            as Augrp,
      _but000.title_let        as Title_Let,
      _but000.bu_logsys        as Bu_Logsys,
      _but000.contact          as Contact,
      _but000.not_released     as Not_Released,
      _but000.not_lg_competent as Not_Lg_Competent,
      _but000.print_mode       as Print_Mode,
      _but000.bp_eew_dummy     as Bp_Eew_Dummy,
      _but000.rate             as Rate,
      _but000.name_org1        as Name_Org1,
      _but000.name_org2        as Name_Org2,
      _but000.name_org3        as Name_Org3,
      _but000.name_org4        as Name_Org4,
      _but000.legal_enty       as Legal_Enty,
      _but000.ind_sector       as Ind_Sector,
      _but000.legal_org        as Legal_Org,
      _but000.dc_not_req       as Dc_Not_Req,
      _but000.found_dat        as Found_Dat,
      _but000.liquid_dat       as Liquid_Dat,
      _but000.location_1       as Location_1,
      _but000.location_2       as Location_2,
      _but000.location_3       as Location_3,
      _but000.name_last        as Name_Last,
      _but000.name_first       as Name_First,
      _but000.name_lst2        as Name_Lst2,
      _but000.name_last2       as Name_Last2,
      _but000.namemiddle       as Name_middle,
      _but000.title_aca1       as Title_Aca1,
      _but000.title_aca2       as Title_Aca2,
      _but000.title_royl       as Title_Royl,
      _but000.prefix1          as Prefix1,
      _but000.prefix2          as Prefix2,
      _but000.name1_text       as Name1_Text,
      _but000.nickname         as Nickname,
      _but000.initials         as Initials,
      _but000.nameformat       as Nameformat,
      _but000.namcountry       as Namcountry,
      _but000.langu_corr       as Langu_Corr,
      _but000.xsexm            as Xsexm,
      _but000.xsexf            as Xsexf,
      _but000.birthpl          as Birthpl,
      _but000.marst            as Marst,
      _but000.emplo            as Emplo,
      _but000.jobgr            as Jobgr,
      _but000.natio            as Natio,
      _but000.cntax            as Cntax,
      _but000.cndsc            as Cndsc,
      _but000.persnumber       as Persnumber,
      _but000.xsexu            as Xsexu,
      _but000.xubname          as Xubname,
      _but000.bu_langu         as Bu_Langu,
      _but000.gender           as Gender,
      _but000.birthdt          as Birthdt,
      _but000.deathdt          as Deathdt,
      _but000.perno            as Perno,
      _but000.children         as Children,
      _but000.mem_house        as MemHouse,
      _but000.birthdt_status   as Birthdt_Status,
      _but000.partgrptyp       as Partgrptyp,
      _but000.name_grp1        as NameGrp1,
      _but000.name_grp2        as NameGrp2,
      _but000.mc_name1         as McName1,
      _but000.mc_name2         as McName2,
      _but000.crusr            as Crusr,
      _but000.crdat            as Crdat,
      _but000.crtim            as Crtim,
      _but000.chusr            as Chusr,
      _but000.chdat            as Chdat,
      _but000.chtim            as Chtim,
      _but000.partner_guid     as PartnervGuid,
      _but000.addrcomm         as Addrcomm,
      _but000.td_switch        as Td_Switch,
      _but000.is_org_centre    as Is_Org_Centre,
      _but000.db_key           as Db_Key,
      _but000.valid_from       as Valid_From,
      _but000.valid_to         as Valid_To,
      _but000.xpcpt            as Xpcpt,
      _but000.data_ctrlr1      as Data_Ctrlr1,
      _but000.data_ctrlr2      as Data_Ctrlr2,
      _but000.data_ctrlr3      as Data_Ctrlr3,
      _but000.data_ctrlr4      as Data_Ctrlr4,
      _but000.data_ctrlr5      as Data_Ctrlr5,
      _but000.data_ctrlr6      as Data_Ctrlr6,
      _but000.data_ctrlr7      as Data_Ctrlr7,
      _but000.data_ctrlr8      as Data_Ctrlr8,
      _but000.data_ctrlr9      as Data_Ctrlr9,
      _but000.data_ctrlr10     as Data_Ctrlr10,
      _but000.xdcset           as Xdcset,
      _but000./ceeib/sk_resid  as /ceeib/sk_Resid,
      _but000.bank_area        as BankArea,
      _but000.credit_tax_code  as Credit_Tax_Code,
      _but000.debit_tax_code   as Debit_Tax_Code,
      _but000.credit_tax_type  as Credit_Tax_Type,
      _but000.debit_tax_type   as Debit_Tax_Type,
      _but000.natpers          as Natpers,
      _but000.milve            as Milve,
      _but000.nuc_sec          as Nuc_Sec,
      _but000.par_rel          as Par_Rel,
      _but000.bp_sort          as Bp_Sort,
      _but000.kbanks           as Kbanks,
      _but000.kbankl           as Kbankl,
      knvi.taxkd               as Taxkd
}
