PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZMASS_V_PARALLEL-APPL_ID .
    FIELD ZMASS_V_PARALLEL-PARALLEL .
    FIELD ZMASS_V_PARALLEL-SERVER_GROUP .
    FIELD ZMASS_V_PARALLEL-MAX_PROCS .
    FIELD ZMASS_V_PARALLEL-MAX_UTILIZATION .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZMASS_V_PARALLEL-APPL_ID .
  module detail_pai.
 endchain.
